package dev.noahtownsend.linkedlicense.plugin

import dev.noahtownsend.linkedlicense.plugin.testsupport.FixtureProject
import dev.noahtownsend.linkedlicense.plugin.testsupport.MavenFixtureRepo
import org.junit.jupiter.api.io.TempDir
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class OverridesFileScaffoldFunctionalTest {
    @TempDir
    lateinit var projectDir: File

    private val expectedScaffold =
        """
        # generated by linkedlicense — see https://github.com/noahddtownsend/LinkedLicense#3-configuring-the-plugin

        [overrides]
        # "group:artifact" = { license = "Apache2" }

        [ignored]
        # "group:artifact" = "reason"

        [copyleft-allowed]
        # "group:artifact" = "reason"

        [license-policy]
        # allow = ["MIT", "Apache2"]
        # block = ["Gpl3"]

        [assets]
        # "asset-id" = { license = "MIT", elementLicensed = "...", author = "...", year = "..." }

        [suppress-best-guess-warnings]
        # "npm:package-name" = "reason"

        """.trimIndent() + "\n"

    @Test
    fun `generateLicenseCatalog scaffolds linkedlicense-toml when it is absent`() {
        val repo = MavenFixtureRepo(File(projectDir, "repo"))
        repo.publish(group = "com.example", artifact = "known-lib", version = "1.0", licenseName = "Apache License, Version 2.0")

        val fixture = FixtureProject(projectDir, repo)
        fixture.writeSettings()
        fixture.writeBuildFile(dependencyCoordinates = listOf("com.example:known-lib:1.0"))

        val overridesFile = File(projectDir, "linkedlicense.toml")
        val result = fixture.run("generateLicenseCatalog")

        assertTrue(result.output.contains("BUILD SUCCESSFUL"), result.output)
        assertTrue(overridesFile.exists())
        assertEquals(expectedScaffold, overridesFile.readText())
    }

    @Test
    fun `generateLicenseCatalog leaves an existing non-empty linkedlicense-toml untouched`() {
        val repo = MavenFixtureRepo(File(projectDir, "repo"))
        repo.publish(group = "com.example", artifact = "unknown-lib", version = "1.0", licenseName = null)

        val fixture = FixtureProject(projectDir, repo)
        fixture.writeSettings()
        fixture.writeBuildFile(dependencyCoordinates = listOf("com.example:unknown-lib:1.0"))
        val existingContent =
            """
            [overrides]
            "com.example:unknown-lib" = { license = "Apache2" }
            """.trimIndent()
        fixture.writeOverridesToml(existingContent)

        val result = fixture.run("generateLicenseCatalog")

        assertTrue(result.output.contains("BUILD SUCCESSFUL"), result.output)
        assertEquals(existingContent, File(projectDir, "linkedlicense.toml").readText())
    }

    @Test
    fun `generateLicenseCatalog leaves an existing empty linkedlicense-toml untouched and still fails on unknown`() {
        val repo = MavenFixtureRepo(File(projectDir, "repo"))
        repo.publish(group = "com.example", artifact = "unknown-lib", version = "1.0", licenseName = null)

        val fixture = FixtureProject(projectDir, repo)
        fixture.writeSettings()
        fixture.writeBuildFile(dependencyCoordinates = listOf("com.example:unknown-lib:1.0"))
        fixture.writeOverridesToml("")

        val result = fixture.runAndFail("generateLicenseCatalog")

        assertTrue(result.output.contains("com.example:unknown-lib:1.0"), result.output)
        assertEquals("", File(projectDir, "linkedlicense.toml").readText())
    }
}
