package dev.noahtownsend.linkedlicense.plugin

import java.nio.file.Files
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class OverridesFileScaffoldTest {
    private val tempDir = Files.createTempDirectory("linkedlicense-scaffold-test").toFile()

    @AfterTest
    fun cleanup() {
        tempDir.deleteRecursively()
    }

    private val expectedContent =
        """
        # generated by linkedlicense — see https://github.com/noahddtownsend/LinkedLicense#3-configuring-the-plugin

        [overrides]
        # "group:artifact" = { license = "Apache2" }

        [ignored]
        # "group:artifact" = "reason"

        [copyleft-allowed]
        # "group:artifact" = "reason"

        [license-policy]
        # allow = ["MIT", "Apache2"]
        # block = ["Gpl3"]

        [assets]
        # "asset-id" = { license = "MIT", elementLicensed = "...", author = "...", year = "..." }

        [suppress-best-guess-warnings]
        # "npm:package-name" = "reason"

        """.trimIndent() + "\n"

    @Test
    fun `ensureExists() creates the file with the fully scaffolded content when it does not exist`() {
        val file = tempDir.resolve("linkedlicense.toml")

        OverridesFileScaffold.ensureExists(file)

        assertTrue(file.exists())
        assertEquals(expectedContent, file.readText())
    }

    @Test
    fun `ensureExists() does not modify a file that already exists with real content`() {
        val file = tempDir.resolve("linkedlicense.toml")
        val existingContent =
            """
            [overrides]
            "com.example:foo" = { license = "Apache2" }
            """.trimIndent()
        file.writeText(existingContent)
        val mtimeBefore = file.lastModified()

        OverridesFileScaffold.ensureExists(file)

        assertEquals(existingContent, file.readText())
        assertEquals(mtimeBefore, file.lastModified())
    }

    @Test
    fun `ensureExists() does not modify a file that already exists but is empty`() {
        val file = tempDir.resolve("linkedlicense.toml")
        file.writeText("")
        val mtimeBefore = file.lastModified()

        OverridesFileScaffold.ensureExists(file)

        assertEquals("", file.readText())
        assertEquals(mtimeBefore, file.lastModified())
    }

    @Test
    fun `the scaffolded file parses to the same empty config as no file at all`() {
        val file = tempDir.resolve("linkedlicense.toml")
        OverridesFileScaffold.ensureExists(file)

        val config = TomlOverridesParser.parse(file, resolveAlias = { it })

        assertEquals(OverridesConfig.EMPTY, config)
    }
}
