package dev.noahtownsend.linkedlicense.plugin

import java.io.File

/**
 * Scaffolds `linkedlicense.toml` the first time a `generateLicenseCatalog`/
 * `generate<SourceSet>LicenseCatalog` task runs against a project that doesn't have one yet
 * (README §3.1 "Auto-generated on first run"): every table the file supports -
 * `[overrides]`, `[ignored]`, `[copyleft-allowed]`, `[license-policy]`, `[assets]` (§3.7), and
 * `[suppress-best-guess-warnings]` (§2.3) - is present with a
 * header comment and a commented-out example line, so the shape of a table you haven't needed
 * yet never has to be looked up in the README.
 *
 * Only fires when [file] is genuinely absent. An existing file, even an empty one, is never
 * touched, overwritten, or appended to.
 */
internal object OverridesFileScaffold {
    private val CONTENT =
        """
        # generated by linkedlicense — see https://github.com/noahddtownsend/LinkedLicense#3-configuring-the-plugin

        [overrides]
        # "group:artifact" = { license = "Apache2" }

        [ignored]
        # "group:artifact" = "reason"

        [copyleft-allowed]
        # "group:artifact" = "reason"

        [license-policy]
        # allow = ["MIT", "Apache2"]
        # block = ["Gpl3"]

        [assets]
        # "asset-id" = { license = "MIT", elementLicensed = "...", author = "...", year = "..." }

        [suppress-best-guess-warnings]
        # "npm:package-name" = "reason"

        """.trimIndent() + "\n"

    fun ensureExists(file: File) {
        if (file.exists()) {
            return
        }

        file.parentFile?.mkdirs()
        file.writeText(CONTENT)
    }
}
